import { jsonResponse, parseRequest, structuredCompletion } from './_openai.js';
import { isTooSimilar, passageRecord, recentHistoryForPrompt } from '../lib/passage-history.js';
import { assertFourChoiceQuestions } from '../lib/assessment.js';

const audit={type:'object',additionalProperties:false,required:['commonKnowledgeAnswerable','passageSpecificEvidence','specialistKnowledgeRequired','properNounRecall'],properties:{commonKnowledgeAnswerable:{type:'boolean'},passageSpecificEvidence:{type:'boolean'},specialistKnowledgeRequired:{type:'boolean'},properNounRecall:{type:'boolean'}}};
const question = { type:'object', additionalProperties:false, required:['prompt','choices','answer','explanation','evidence','audit'], properties:{ prompt:{type:'string'}, choices:{type:'array',minItems:4,maxItems:4,items:{type:'string'}}, answer:{type:'integer',minimum:0,maximum:3}, explanation:{type:'string'}, evidence:{type:'string'}, audit } };
const passage = { type:'object', additionalProperties:false, required:['id','title','topic','category','caseType','settingType','fictionalEntityName','organizationUsed','keyMechanism','outcome','argumentPattern','shortSummary','centralThesis','keywords','mainExamples','passage','translation','questions'], properties:{ id:{type:'string'}, title:{type:'string'}, topic:{type:'string'}, category:{type:'string'}, caseType:{type:'string'}, settingType:{type:'string',enum:['fictional','real']}, fictionalEntityName:{type:'string'}, organizationUsed:{type:'string'}, keyMechanism:{type:'string'}, outcome:{type:'string'}, argumentPattern:{type:'string'}, shortSummary:{type:'string'}, centralThesis:{type:'string'}, keywords:{type:'array',minItems:4,maxItems:10,items:{type:'string'}}, mainExamples:{type:'array',minItems:2,maxItems:6,items:{type:'string'}}, passage:{type:'string'}, translation:{type:'string'}, questions:{type:'array',minItems:3,maxItems:3,items:question} } };
const categoryGroups = [
  'workplace operations, human resources, staff training, customer service, office facilities, or internal project management',
  'retail, product information, shipping, logistics, purchasing, sales, hospitality, business travel, or event scheduling',
  'a company announcement, community service, public facility, practical technology rollout, professional development, or local business partnership',
];

export default async function handler(request,response) {
  if (request.method !== 'POST') return jsonResponse(response,405,{error:'Method not allowed'});
  try {
    const input=parseRequest(request); const recent=recentHistoryForPrompt(Array.isArray(input.recentPassages)?input.recentPassages:[]); const historyText=JSON.stringify(recent).slice(0,14000);
    const create=async(slot,extra='')=>structuredCompletion({
      system:'You design high-quality TOEIC-oriented English speed-reading practice. Return only valid structured data. Every answer must be uniquely supported by its document. Use practical workplace and business English, realistic details, paraphrase, scheduling, purpose, inference, and information processing—not rare academic vocabulary.',
      user:`Create one TOEIC-style English reading document of 190–220 words for slot ${slot+1} of a three-document set. Choose its context from ${categoryGroups[slot]}. Vary the document form among an internal email, memo, notice, announcement, business letter, customer message, web page, short report, schedule update, or workplace article. Make it a realistic fictional situation with specific dates, conditions, responsibilities, changes, exceptions, costs, deadlines, or unexpected outcomes; mark the entity internally with settingType="fictional" and fictionalEntityName. Do not imitate or name an actual TOEIC question. Avoid academic essays and generic “benefits and risks” discussion. Compare it with history by domain, document/case type, organizationUsed, keyMechanism, outcome, argumentPattern, keywords, and examples. RECENT PASSAGES: ${historyText}. Use practical CEFR B1–B2 vocabulary commonly encountered in TOEIC preparation. Draft questions and ask: “Could a reasonably educated person answer this correctly without reading the document?” Reject any question if yes. Return exactly 3 questions covering purpose or main point, a passage-specific detail or condition, and inference/paraphrase. Do not ask merely for a company name. Set every audit truthfully: commonKnowledgeAnswerable=false, passageSpecificEvidence=true, specialistKnowledgeRequired=false, properNounRecall=false. Each question must have exactly 4 plausible, balanced options; only document details may distinguish the answer. Each option should normally be 12–28 words with similar length and style. explanation must state why the answer follows and why each distractor fails. evidence must include enough wording from the document for code-side verification. Provide all requested case metadata plus a natural complete Japanese translation. ${extra}`,
      schema:passage,
    });
    const passages=await Promise.all([0,1,2].map((slot)=>create(slot))); const accepted=[...recent]; const retry=[];
    passages.forEach((item,index)=>{let invalid=false;try{if(!item.translation)throw new Error();assertFourChoiceQuestions(item.questions,3,'quick',item.passage);}catch{invalid=true;}const record=passageRecord(item,'quick');if(invalid||isTooSimilar(record,accepted))retry.push(index);else accepted.push(record);});
    await Promise.all(retry.map(async(index)=>{passages[index]=await create(index,'The first draft failed novelty or passage-dependency checks. Change its case structure, mechanism, outcome, and examples; replace any common-knowledge or proper-name recall question.');}));
    jsonResponse(response,200,passages);
  } catch (error) { jsonResponse(response,503,{error:error.message}); }
}
