import { jsonResponse, parseRequest, structuredCompletion } from './_openai.js';
import { isTooSimilar, passageRecord, recentHistoryForPrompt } from '../lib/passage-history.js';
import { validateQuickSet } from '../lib/assessment.js';

const audit={type:'object',additionalProperties:false,required:['commonKnowledgeAnswerable','passageSpecificEvidence','specialistKnowledgeRequired','properNounRecall'],properties:{commonKnowledgeAnswerable:{type:'boolean'},passageSpecificEvidence:{type:'boolean'},specialistKnowledgeRequired:{type:'boolean'},properNounRecall:{type:'boolean'}}};
const question = { type:'object', additionalProperties:false, required:['prompt','choices','answer','explanation','evidence','audit'], properties:{ prompt:{type:'string'}, choices:{type:'array',minItems:4,maxItems:4,items:{type:'string'}}, answer:{type:'integer',minimum:0,maximum:3}, explanation:{type:'string'}, evidence:{type:'string'}, audit } };
const passage = { type:'object', additionalProperties:false, required:['id','title','topic','category','caseType','settingType','fictionalEntityName','organizationUsed','keyMechanism','outcome','argumentPattern','shortSummary','centralThesis','keywords','mainExamples','passage','translation','questions'], properties:{ id:{type:'string'}, title:{type:'string'}, topic:{type:'string'}, category:{type:'string'}, caseType:{type:'string'}, settingType:{type:'string',enum:['fictional','real']}, fictionalEntityName:{type:'string'}, organizationUsed:{type:'string'}, keyMechanism:{type:'string'}, outcome:{type:'string'}, argumentPattern:{type:'string'}, shortSummary:{type:'string'}, centralThesis:{type:'string'}, keywords:{type:'array',minItems:4,maxItems:10,items:{type:'string'}}, mainExamples:{type:'array',minItems:2,maxItems:6,items:{type:'string'}}, passage:{type:'string'}, translation:{type:'string'}, questions:{type:'array',minItems:3,maxItems:3,items:question} } };
const schema = { type:'object', additionalProperties:false, required:['passages'], properties:{ passages:{type:'array',minItems:3,maxItems:3,items:passage} } };

export default async function handler(request,response) {
  if (request.method !== 'POST') return jsonResponse(response,405,{error:'Method not allowed'});
  try {
    const input=parseRequest(request); const recent=recentHistoryForPrompt(Array.isArray(input.recentPassages)?input.recentPassages:[]); const historyText=JSON.stringify(recent).slice(0,14000);
    const create=async(extra='')=>structuredCompletion({
      system:'You design high-quality English speed-reading practice. Return only valid structured data. Every answer must be uniquely supported by its passage. Quick difficulty should come from speed, paraphrase, information processing, and accuracy—not a concentration of rare vocabulary.',
      user:`Create exactly 3 independent English passages of 190–220 words in three different categories selected from science, medicine, psychology, economics, history, philosophy, anthropology, linguistics, sociology, environment, biology, technology, education, culture, public policy, architecture, archaeology, behavioral science, agriculture, logistics, water systems, and daily life. Prefer concrete cases: a realistic fictional company, study, city, institution, policy experiment, scientific observation, obscure historical episode, comparison, failed project, or unexpected finding. Avoid generic “benefits and risks” essays and claims that can be guessed from common knowledge. Fictional cases need distinctive business models, policies, mechanisms, decisions, disagreements, chronology, and outcomes; mark them internally with settingType="fictional" and fictionalEntityName. Real cases must provide every fact needed, without requiring specialist knowledge. Avoid categories used in the most recent three records when practical. Compare each new passage with history by domain, thesis, caseType, settingType, organizationUsed, keyMechanism, outcome, argumentPattern, keywords, and examples—not merely title. The three new passages must also differ structurally from one another. RECENT PASSAGES: ${historyText}. Use accessible but substantive English around CEFR B2. For each passage, draft questions and ask: “Could a reasonably educated person answer this correctly without reading the passage?” Reject any question if yes. Also reject specialist-knowledge and proper-name recall questions. Return exactly 3 questions whose answers depend on passage-specific cause, exception, chronology, comparison, interpretation, or unexpected result. Set every audit truthfully: commonKnowledgeAnswerable=false, passageSpecificEvidence=true, specialistKnowledgeRequired=false, properNounRecall=false. Each question must have exactly 4 generally plausible, balanced options; only passage details may distinguish the answer. Each option should normally be 14–32 words with similar length, syntax, specificity, and style. explanation must state why the correct option follows and why each distractor fails. evidence must include enough wording from the passage for code-side verification. Provide all requested case metadata for story-structure duplicate detection, plus a natural complete Japanese translation. ${extra}`,
      schema,
    });
    let data=await create(); const accepted=[];
    const duplicate=data.passages.some((item)=>isTooSimilar(passageRecord(item,'quick'),[...recent,...accepted])?true:(accepted.push(passageRecord(item,'quick')),false));
    let invalid=false; try{validateQuickSet(data.passages);}catch{invalid=true;}
    if(duplicate||invalid)data=await create('The first set failed novelty or passage-dependency checks. Replace overlapping case structures and replace any common-knowledge or proper-name recall question with one requiring passage-specific reasoning.');
    jsonResponse(response,200,data.passages);
  } catch (error) { jsonResponse(response,503,{error:error.message}); }
}
