import { jsonResponse, parseRequest, structuredCompletion } from './_openai.js';
import { isTooSimilar, passageRecord, recentHistoryForPrompt } from '../lib/passage-history.js';
import { assertFourChoiceQuestions } from '../lib/assessment.js';

const audit={type:'object',additionalProperties:false,required:['commonKnowledgeAnswerable','passageSpecificEvidence','specialistKnowledgeRequired','properNounRecall'],properties:{commonKnowledgeAnswerable:{type:'boolean'},passageSpecificEvidence:{type:'boolean'},specialistKnowledgeRequired:{type:'boolean'},properNounRecall:{type:'boolean'}}};
const question = { type:'object', additionalProperties:false, required:['prompt','choices','answer','explanation','evidence','audit'], properties:{ prompt:{type:'string'}, choices:{type:'array',minItems:4,maxItems:4,items:{type:'string'}}, answer:{type:'integer',minimum:0,maximum:3}, explanation:{type:'string'}, evidence:{type:'string'}, audit } };
const passage = { type:'object', additionalProperties:false, required:['id','title','topic','category','caseType','settingType','fictionalEntityName','organizationUsed','keyMechanism','outcome','argumentPattern','shortSummary','centralThesis','keywords','mainExamples','passage','translation','questions'], properties:{ id:{type:'string'}, title:{type:'string'}, topic:{type:'string'}, category:{type:'string'}, caseType:{type:'string'}, settingType:{type:'string',enum:['fictional','real']}, fictionalEntityName:{type:'string'}, organizationUsed:{type:'string'}, keyMechanism:{type:'string'}, outcome:{type:'string'}, argumentPattern:{type:'string'}, shortSummary:{type:'string'}, centralThesis:{type:'string'}, keywords:{type:'array',minItems:4,maxItems:10,items:{type:'string'}}, mainExamples:{type:'array',minItems:2,maxItems:6,items:{type:'string'}}, passage:{type:'string'}, translation:{type:'string'}, questions:{type:'array',minItems:3,maxItems:3,items:question} } };
const categoryGroups = [
  'science, medicine, biology, psychology, or behavioral science',
  'history, philosophy, anthropology, archaeology, linguistics, or culture',
  'economics, public policy, architecture, technology, education, agriculture, logistics, water systems, or daily life',
];

export default async function handler(request,response) {
  if (request.method !== 'POST') return jsonResponse(response,405,{error:'Method not allowed'});
  try {
    const input=parseRequest(request); const recent=recentHistoryForPrompt(Array.isArray(input.recentPassages)?input.recentPassages:[]); const historyText=JSON.stringify(recent).slice(0,14000);
    const create=async(slot,extra='')=>structuredCompletion({
      system:'You design high-quality English speed-reading practice. Return only valid structured data. Every answer must be uniquely supported by its passage. Quick difficulty should come from speed, paraphrase, information processing, and accuracy—not a concentration of rare vocabulary.',
      user:`Create one English speed-reading passage of 190–220 words for slot ${slot+1} of a three-passage set. Choose its category from ${categoryGroups[slot]}; this division keeps the three parallel slots distinct. Prefer a concrete case: a realistic fictional company, study, city, institution, policy experiment, scientific observation, obscure historical episode, comparison, failed project, or unexpected finding. Avoid generic “benefits and risks” essays and claims guessable from common knowledge. Fictional cases need distinctive policies, mechanisms, decisions, chronology, and outcomes; mark them internally with settingType="fictional" and fictionalEntityName. Real cases must provide every fact needed without specialist knowledge. Compare it with history by domain, thesis, caseType, settingType, organizationUsed, keyMechanism, outcome, argumentPattern, keywords, and examples—not merely title. RECENT PASSAGES: ${historyText}. Use accessible but substantive English around CEFR B2. Draft questions and ask: “Could a reasonably educated person answer this correctly without reading the passage?” Reject any question if yes. Also reject specialist-knowledge and proper-name recall questions. Return exactly 3 questions whose answers depend on passage-specific cause, exception, chronology, comparison, interpretation, or unexpected result. Set every audit truthfully: commonKnowledgeAnswerable=false, passageSpecificEvidence=true, specialistKnowledgeRequired=false, properNounRecall=false. Each question must have exactly 4 generally plausible, balanced options; only passage details may distinguish the answer. Each option should normally be 14–32 words with similar length, syntax, specificity, and style. explanation must state why the correct option follows and why each distractor fails. evidence must include enough wording from the passage for code-side verification. Provide all requested case metadata plus a natural complete Japanese translation. ${extra}`,
      schema:passage,
    });
    const passages=await Promise.all([0,1,2].map((slot)=>create(slot))); const accepted=[...recent]; const retry=[];
    passages.forEach((item,index)=>{let invalid=false;try{if(!item.translation)throw new Error();assertFourChoiceQuestions(item.questions,3,'quick',item.passage);}catch{invalid=true;}const record=passageRecord(item,'quick');if(invalid||isTooSimilar(record,accepted))retry.push(index);else accepted.push(record);});
    await Promise.all(retry.map(async(index)=>{passages[index]=await create(index,'The first draft failed novelty or passage-dependency checks. Change its case structure, mechanism, outcome, and examples; replace any common-knowledge or proper-name recall question.');}));
    jsonResponse(response,200,passages);
  } catch (error) { jsonResponse(response,503,{error:error.message}); }
}
